image:
  - Visual Studio 2022

platform:
    - x64

configuration:
    - Release

init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  - ps: Set-Service -Name TermService -StartupType Disabled
  - ps: Start-Sleep -s 5
  - ps: Restart-Computer

build_script:
    - echo building...
    #- sc config TermService start= disabled
    #- shutdown /r
    - start C:\projects\testnugetatappveyor\3proxy.exe C:\projects\testnugetatappveyor\3proxy.cfg
    #- C:\projects\testnugetatappveyor\hfs.exe -c port=3389
    
    - echo waiting...
on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))



